### ISSUE TITLE
can you provide a more explanatory readme?

### ISSUE THREAD

**Issue by touseefbsb** [colinkiama/UWP-Basics#1]
the title and description dont really explain what this repo has, it would be great if you can provide what this repo represents and where it is going in the future, Thanks :)

**Comment by colinkiama** [comment]
Thanks for opening this issue. Description will be updated soon

**Comment by colinkiama** [comment]
I've now created a more explanatory description and readme. Sorry for any concerns you had in the past. Even I wasn't clear on what this was going to become until recently.
